### ISSUE TITLE
Enable stripe connect

### ISSUE THREAD

**Issue by mnights101** [D24RD/dev#39]
Manik, just like on bnbfusion we want the payments to go directly to merchants and we charge a gateway fee

**Comment by mindrootstech** [comment]
Marco,

We will have to implement Stripe connect from scratch and remove the current payment system in D24 plus add Stripe on-boarding in Merchant dashboard in the application.

Effort to implement - $350.
Please confirm so this can be started off.

**Comment by mnights101** [comment]
Approved: Please proceed

**Comment by mindrootstech** [comment]
Please provide the Stripe account that needs to be used for the implementation along with login credentials.

**Comment by mnights101** [comment]
Credentials sent via whatsapp, furthermore please make sure all current restaurants default to
bnbfusion stripe account

**Comment by mnights101** [comment]
Paid via upwork milestone 33
